version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        image: easy-wallet-app
        container_name: easy-wallet-app
        restart: on-failure
        volumes:
            - .:/var/www
        working_dir: /var/www
        entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]
        depends_on:
            mysql:
                condition: service_healthy

    nginx:
        image: nginx:alpine
        container_name: easy-wallet-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql-container
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 10s
            retries: 3
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    dbdata:
